spring:
  application:
    name: "UracleFrameWork"
  output:
    ansi:
      enabled: detect

  datasource:
    url: ${DB_URL}?useUnicode=true&characterEncoding=AL32UTF8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
server:
  tomcat:
    additional-tld-skip-patterns:
    - "*.jar"