spring:
  application:
    name: "UracleFrameWork"
  output:
    ansi:
      enabled: detect
  datasource:
    url: jdbc:oracle:thin:@localhost:1523/DBTVDB?useUnicode=true&characterEncoding=AL32UTF8
    username: BTVSMS
    password: smsbtv6266!#
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

AES:
  default:
    algorithm: AES/CBC/PKCS5Padding
    key: aql201koer0123axz1sdk30z0-d1sssz
    iv: wke221sxzxclqowa
  test:
    algorithm: AES/GCM/NoPadding
    key: aql201koer0123axz1sdk30z0-d1sssz
    iv: wke221sxzxclqowa



mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
server:
  tomcat:
    additional-tld-skip-patterns:
    - "*.jar"

filter:
  decryptionMappings:
    - decryptionMethod: "SHA-512"
      headers:
        - "header1"
        - "header2"
    - decryptionMethod: "SHA-256"
      headers:
        - "header3"
        - "header4"
